### ISSUE TITLE
Mads dependency

### ISSUE THREAD

**Issue by orenbenkiki** [SmartTensors/NMFk.jl#32]
`Mads` is only used for plotting in examples and notebooks. It brings with it a **huge** set of dependencies (>400!), the vast majority of which aren't needed for just computing the NMF model (which is all I need).

Julia doesn't have Rust's notion of package "features", which would have been ideal here :-(

A workaround would be to split the computation code into a separate `ComputeNMFk` package and make it a dependency of `NMFk` (and re-export everything from it, for 100% backward compatibility with the current implementation).

This would allow importing just the `ComputeNMFk` package if the notebook/display functionality isn't needed.

**Comment by montyvesselinov** [comment]
I agree. We are working on addressing these issues.
